name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-release:
    name: Build and Upload Binaries
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: rsopen
            asset_name: rsopen-linux-amd64
          - os: windows-latest
            artifact_name: rsopen.exe
            asset_name: rsopen-windows-amd64.exe
          - os: macos-latest
            artifact_name: rsopen
            asset_name: rsopen-macos-amd64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-musl

      - name: Install Musl Tools
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install -y musl-tools

      - name: Build Release
        run: |
          if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
            cargo build --release --target x86_64-unknown-linux-musl
            mv target/x86_64-unknown-linux-musl/release/${{ matrix.artifact_name }} target/release/
          else
            cargo build --release
          fi

      - name: Upload Binary to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/${{ matrix.artifact_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}
          overwrite: true

  publish-crate:
    name: Publish to Crates.io
    runs-on: ubuntu-latest
    needs: build-release
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Publish to Crates.io
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: cargo publish
